#!/bin/bash
#PBS -N mpi
#PBS -l nodes=1:ppn=8
#PBS walltime=1000:00:00
#PBS -j oe

cd $PBS_O_WORKDIR
procs = $(cat $PBS_NODEFILE | wc -l)

echo "" > mpi.log
for((n=8;n<=13;n+=1))
do
    for((tn=1, rtn=2;tn<=8;tn*=2, rtn=tn+1))
    do
        echo "data size:$n×$n  process number:$rtn" >>mpi.log
        for((i=0;i<10;i++))
        do
            mpirun -np $rtn ./mpi $n numbers.txt $procs >>mpi.log
        done
    done
done
